# Generated by Django 5.0.1 on 2024-01-17 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_youtube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
