# Generated by Django 5.0.1 on 2024-01-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_delete_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duraction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
