# Generated by Django 5.0.1 on 2024-01-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_course_duraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='admin/companies')),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
