# Generated by Django 5.0.1 on 2024-01-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_gallery_placement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Companies',
            new_name='Company',
        ),
    ]
