# Generated by Django 5.0.1 on 2024-01-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_rename_companies_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='shorts_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='yt_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
