# Generated by Django 4.1 on 2024-07-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_contactmessage_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
